### ISSUE TITLE
Work with 443mhz sensor

### ISSUE THREAD

**Issue by garudaonekh** [Lynxmotion/Arduino-PPM#1]
Hi,
I need library to decode data from 433HMZ sensor using Superheterodyne Receiver. The sensor use OOK PPM.
Will your library work with it? And I use ESP32, this code is arduino, will it be compatible?

Thanks;

**Comment by guru-florida** [comment]
OOK is manchester encoding. My *guess* is if the product is saying OOK PPM, then OOK is the over-the-air transmission protocol using manchester/OOK at FM 433MHz which doesn't really matter to you (transmission details)...the receiver is decoding the OOK and probably outputting regular PPM code. 

However this code is only AVR compatible. It could be adapted to ESP32 pretty easily. Pull Requests welcome!

# Development Guide
The only possibly incompatible part is assigning the ISR function to a pin. The old Arduino AVR interrupt lib code had a bug so pcint.h/cpp was used to get around it, but I think this is fixed in Arduino now and works across archs. The pin must support the "pin change" interrupt. So if you want to give it a shot:
* download code and add to your local arduino "libraries" directory. 
* add a ".development" empty dummy file to the Arduino-PPM base dir so you can edit and save the examples without the "must save-as" prompt getting in the way
* Add "esp32" architecture to library.properties "architecture" line (not sure what the actual arch word is here for esp32)
* modify src/ppm.cpp. Disable the USE_PCINT maco near the top for ESP archs and test. Something around PPM::begin() might need to change with how the ISR routine is attached to an interrupt pin...but might work fine as-is once USE_PCINT is disabled.

**Comment by garudaonekh** [comment]
thanks for the detail
